#!/bin/sh
set -e

echo "Activating feature 'confluence-cli'"

# Option values (provided by the devcontainer CLI as environment variables:
# the option id uppercased, non-alphanumerics replaced with '_').
BASE_URL="${BASE_URL:-}"
USER_NAME="${USER_NAME:-}"
USER_PASSWORD="${USER_PASSWORD:-}"

# Shared, world-readable location for uv's tool data so the installed CLI is
# runnable by the (non-root) remote user too; the launcher is placed on PATH.
UV_ROOT=/opt/uv
export UV_TOOL_DIR="$UV_ROOT/tools"
export UV_PYTHON_INSTALL_DIR="$UV_ROOT/python"
export UV_TOOL_BIN_DIR=/usr/local/bin

# --- ensure uv is available --------------------------------------------------
if ! command -v uv >/dev/null 2>&1; then
    if ! command -v curl >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y --no-install-recommends curl ca-certificates
    fi
    # Install uv (and uvx) into a system-wide location on PATH, without letting
    # the installer edit any shell profiles.
    export UV_INSTALL_DIR=/usr/local/bin
    export INSTALLER_NO_MODIFY_PATH=1
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

UV="$(command -v uv || echo /usr/local/bin/uv)"

# --- install the CLI from PyPI -----------------------------------------------
# The published package `kci-confluence-cli` provides the `confluence` command.
mkdir -p "$UV_ROOT"
"$UV" tool install kci-confluence-cli
# Make the tool environment readable/executable by every user, not just root.
chmod -R a+rX "$UV_ROOT" 2>/dev/null || true

# --- environment variables from options --------------------------------------
# A Feature's containerEnv cannot interpolate option values, so write the
# exports to a profile script (sourced by login shells) and also source it from
# the interactive bash/zsh rc files. NOTE: these values are written into the
# container/image at build time; treat the password accordingly (see README).
squote() {
    # POSIX-safe single-quoting (handles values containing single quotes).
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

ENV_FILE=/etc/profile.d/confluence-cli.sh
if [ -n "$BASE_URL" ] || [ -n "$USER_NAME" ] || [ -n "$USER_PASSWORD" ]; then
    {
        echo '#!/bin/sh'
        echo '# Generated by the confluence-cli devcontainer feature.'
        if [ -n "$BASE_URL" ];      then echo "export CONFLUENCE_BASE_URL=$(squote "$BASE_URL")"; fi
        if [ -n "$USER_NAME" ];     then echo "export CONFLUENCE_USER_NAME=$(squote "$USER_NAME")"; fi
        if [ -n "$USER_PASSWORD" ]; then echo "export CONFLUENCE_USER_PASSWORD=$(squote "$USER_PASSWORD")"; fi
    } > "$ENV_FILE"
    # World-readable (root-owned, like normal /etc/profile.d files): the runtime
    # user is not reliably known at build time, and restricting to a guessed
    # owner makes the file unreadable (so the vars unset) when the actual login
    # user differs. The value is already an env var visible to the user's
    # processes and is baked into the image, so 644 does not widen exposure.
    chmod 644 "$ENV_FILE"

    # Interactive (non-login) bash/zsh shells don't read /etc/profile.d; source
    # it from their global rc files too, idempotently.
    SRC_LINE='[ -f /etc/profile.d/confluence-cli.sh ] && . /etc/profile.d/confluence-cli.sh'
    for rc in /etc/bash.bashrc /etc/zsh/zshrc; do
        if [ -f "$rc" ] && ! grep -qF 'confluence-cli.sh' "$rc"; then
            printf '\n%s\n' "$SRC_LINE" >> "$rc"
        fi
    done
fi

echo "confluence-cli ready: 'confluence' installed on PATH; CONFLUENCE_* env wired via $ENV_FILE"
